# Generated by Django 4.2.3 on 2023-07-27 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="role",
            fields=[
                ("id_role", models.AutoField(primary_key=True, serialize=False)),
                ("role_code", models.CharField(max_length=500)),
                ("role_name", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=500)),
                ("email", models.TextField(max_length=500)),
                ("password", models.TextField(max_length=500)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="login.role",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
