# Generated by Django 4.2.3 on 2023-07-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id_aircraft_type', models.IntegerField(primary_key=True, serialize=False)),
                ('aircraft_name', models.TextField()),
                ('aircraft_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id_airline', models.AutoField(primary_key=True, serialize=False)),
                ('airline_code', models.TextField()),
                ('airline_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id_station', models.IntegerField(primary_key=True, serialize=False)),
                ('station_name', models.TextField()),
                ('station_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_flight_no', models.TextField()),
                ('departure_flight_no', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('monday_operation', models.BooleanField()),
                ('tuesday_operation', models.BooleanField()),
                ('wednesday_operation', models.BooleanField()),
                ('thursday_operation', models.BooleanField()),
                ('friday_operation', models.BooleanField()),
                ('saturday_operation', models.BooleanField()),
                ('sunday_operation', models.BooleanField()),
                ('arrival_time', models.TextField()),
                ('departure_time', models.TextField()),
                ('no_of_seats', models.IntegerField()),
                ('overnight_parking', models.BooleanField()),
                ('service_type_arrival', models.TextField()),
                ('service_type_departure', models.TextField()),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.aircrafttype')),
                ('arrival_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_schedules', to='schedule.airlines')),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_schedules', to='schedule.stations')),
                ('departure_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_schedules', to='schedule.airlines')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_schedules', to='schedule.stations')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_schedules', to='schedule.stations')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_schedules', to='schedule.stations')),
            ],
        ),
    ]
