# Generated by Django 4.2.3 on 2023-07-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aircrafttype',
            table='aircraft_types',
        ),
        migrations.AlterModelTable(
            name='airlines',
            table='airlines',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedules',
        ),
        migrations.AlterModelTable(
            name='stations',
            table='stations',
        ),
    ]
