# Generated by Django 4.2.3 on 2023-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_aircrafttype_table_alter_airlines_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='overnight_parking',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
