# Generated by Django 4.2.3 on 2023-07-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_overnight_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTypes',
            fields=[
                ('id_schedule_type', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_type_name', models.TextField()),
            ],
            options={
                'db_table': 'schedule_types',
            },
        ),
    ]
