# Generated by Django 4.2.3 on 2023-07-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_scheduletypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_schedule_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_types', to='schedule.scheduletypes'),
            preserve_default=False,
        ),
    ]
