# Generated by Django 4.2.3 on 2023-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_schedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TextField(),
        ),
    ]
