# Generated by Django 4.2.3 on 2023-08-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "schedule",
            "0008_rename_schedule_schedules_aircrafttype_aircraft_logo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircrafttype",
            name="id_aircraft_type",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="arrival_flight_no",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="departure_flight_no",
            field=models.IntegerField(),
        ),
     
    ]
