# Generated by Django 4.2.3 on 2023-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0009_alter_aircrafttype_id_aircraft_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedules",
            name="aircraft_regn",
            field=models.TextField(default=""),
        ),
    ]
