# Generated by Django 4.2.3 on 2023-07-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="api_url",
            fields=[
                ("id_api_url", models.AutoField(primary_key=True, serialize=False)),
                ("api_url", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "api_url",
            },
        ),
        migrations.CreateModel(
            name="api_url_access",
            fields=[
                (
                    "id_api_url_access",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="access_info",
                        serialize=False,
                        to="acl.api_url",
                    ),
                ),
                ("get", models.BooleanField(default=False)),
                ("post", models.BooleanField(default=False)),
                ("patch", models.BooleanField(default=False)),
                ("delete", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_url_access",
                        to="login.role",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_details",
                        to="acl.api_url",
                    ),
                ),
            ],
            options={
                "db_table": "api_url_access",
            },
        ),
    ]
